package com.epam.couriers.command;

public enum CommandName {

    OPEN_SIGN_IN,
    SIGN_IN,
    SIGN_OUT,
    SET_LOCALE,
    OPEN_COURIER_REGISTRATION,
    OPEN_CUSTOMER_REGISTRATION,
    COURIER_REGISTRATION,
    CUSTOMER_REGISTRATION,

    ADD_FILLED_CUSTOMER_ORDER,
    OPEN_NEW_ORDER_FORM,
    MAKE_ORDER,

    GET_NEW_COURIERS_RECORDS,
    GET_ALL_COURIERS,
    GET_ALL_ORDERS,
    GET_ALL_TRANSPORT,
    GET_ALL_GOODS,
    TABLE_PAGINATION,
    ACCEPT_COURIER,
    REJECT_COURIER,
    MORE_DETAILS,
    BACK_AFTER_DETAILS


}
